version: '3'
services:
  node-app:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - ./.env

  mongo:
    image: mongo 
    ports:
      - "27017:27017"
    restart: unless-stopped 
    env_file:
      - ./db.env
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: