version: '3'
services:
  node-app:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    # environment:
    # - PORT=5001
    env_file:
      - ./.env
    