version: '3.4'
services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    ports:
      - "5173:5173"
    env_file:
      - ./.env
    container_name: react-app
    volumes:
      - ./src:/app/src:ro
  
    