version: '3'
services:
  web:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "5001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  node-app:
    build: .
    # ports:
    #   - "5001:5001"
    env_file:
      - ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo 
    restart: unless-stopped 
    env_file:
      - ./db.env
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis
    volumes:
      - redis-db:/data/db


volumes:
  mongo-db:
  redis-db:
