version: '3'
services:
  node-app:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - ./.env

  mongo:
    image: mongo  
    env_file:
      - ./db.env
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: