version: '3.4'
services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
      args:
        - NODE_ENV=production
    ports:
      - "8081:80"
    env_file:
      - ./.env
    