version: '3'
services:
  web:
    image: nginx:stable-alpine
    ports:
      - "5001:80"
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - modules:/app/node_modules
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
    command: npm run dev

volumes:
  modules: