# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: 
      - github-actions
  pull_request:
    branches: 
      - github-actions

jobs:
  build:
    name: build client and api
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/


    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }} for client
      if: ${{ github.ref == 'refs/heads/github-actions' }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # cache: 'yarn'

    - name: client
      run: cd client && yarn install --immutable --immutable-cache --check-cache --ignore-engines && yarn run build

    - name: api
      run: cd api && yarn install --immutable --immutable-cache --check-cache --ignore-engines && yarn run start
